### ISSUE TITLE
Trouble opening a specific file

### ISSUE THREAD

**Issue by parkermalenke** [UziTech/atom-open#6]
Hi there,

I'm trying to open a file on my system using this, and while it will open Atom itself I can't seem to get it to open the actual file I am specifying.

For example I am using urls such as:

```
atom://open?url=/Users/{username}/Desktop/test.txt
```
or
```
atom://open?url=/Users/{username}/Documents/Web%20Projects/kiwi/kiwi/activities/2019/2019-01-01-uphill_laps.md
```

Any thoughts?

**Comment by UziTech** [comment]
try opening the console in atom (<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd>) and running:

```
atom.open({["/Users/{username}/Desktop/test.txt"]});
```

Does it open the correct file?

**Comment by parkermalenke** [comment]
Hey, thanks for the response. Yes, it does. Same with the other file. (I found that the shortcut for the mac was cmd + opt + i though).

**Comment by UziTech** [comment]
try

```
atom://open?url=file:///Users/{username}/Desktop/test.txt
```

does it prompt you to open the file? And does the prompt have the correct file listed?

**Comment by parkermalenke** [comment]
No dice, unfortunately. Still just open Atom but not the file. If it helps I'm on the following environment:

- macOS 10.14.1
- Atom 1.35.1
- atom-open 2.0.3

**Comment by UziTech** [comment]
Did it prompt you? Check your settings to make sure your prompt isn't turned off.

**Comment by UziTech** [comment]
Or check the console for any errors

**Comment by parkermalenke** [comment]
I get a prompt from Safari or Chrome asking if I want to open Atom, but no prompt from Atom itself. Should I be getting one from within Atom?

Looks like I do get this error in the console though:

```
Uncaught (in promise) Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Buttons must be an array
Error: Could not call remote function 'showMessageBox'. Check that the function signature is correct. Underlying error: Buttons must be an array
    at callFunction (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at callFunction (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:125:16)
    at ApplicationDelegate.confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:700450)
    at AtomEnvironment.confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688927)
    at confirm (/Users/parker/.atom/packages/open/index.js:66:10)
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/parker/.atom/packages/open/index.js:65:20)
    at Generator.next (<anonymous>)
    at step (/Users/parker/.atom/packages/open/index.js:5:273)
    at /Users/parker/.atom/packages/open/index.js:5:443
    at new Promise (<anonymous>)
    at Object.handleURI (/Users/parker/.atom/packages/open/index.js:5:99)
    at activate.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2941994)
    at <anonymous>
exception @ /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221
metaToValue @ /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:225
remoteMemberFunction @ /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:125
confirm @ VM22 <embedded>:1
confirm @ VM22 <embedded>:1
confirm @ index.js? [sm]:66
(anonymous) @ index.js? [sm]:65
step @ /Users/parker/.atom/packages/open/index.js:5
(anonymous) @ /Users/parker/.atom/packages/open/index.js:5
(anonymous) @ /Users/parker/.atom/packages/open/index.js:5
activate.then @ VM22 <embedded>:11
Promise rejected (async)
step @ /Users/parker/.atom/packages/open/index.js:5
(anonymous) @ /Users/parker/.atom/packages/open/index.js:5
(anonymous) @ /Users/parker/.atom/packages/open/index.js:5
activate.then @ VM22 <embedded>:11
Promise resolved (async)
handleURI @ VM22 <embedded>:11
t.uriHandlerSubscription.packageManager.registerURIHandlerForPackage.e @ VM22 <embedded>:11
handleURI @ VM22 <embedded>:11
dispatchURIMessage @ VM22 <embedded>:1
t @ VM22 <embedded>:1
emitTwo @ events.js:126
emit @ events.js:214
```

**Comment by UziTech** [comment]
Looks like it was an issue with changing the confirm dialog to async.

Thanks for reporting this.

**Comment by parkermalenke** [comment]
Looks like that fixed it—thanks!
