### ISSUE TITLE
Failed to load the open package

### ISSUE THREAD

**Issue by theora** [UziTech/atom-open#68]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [open](https://github.com/UziTech/atom-open) package 2.0.4

### Stack Trace

Failed to load the open package

```
At There is already a URI host handler for the host open

Error: There is already a URI host handler for the host open
    at URIHandlerRegistry.registerHostHandler (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:351037)
    at PackageManager.registerURIHandlerForPackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:382126)
    at Package.registerURIHandler (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3290854)
    at measure (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3285306)
    at Package.measure (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3284372)
    at Package.load (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3285113)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:381274)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:380002)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:382574)
    at ~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:943557
    at r (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:938163)
    at o (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122275)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122481)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -7:36.5.0 linkist:link (span.syntax--text.syntax--plain.syntax--null-grammar)
 21x -6:32 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
click-link 1.0.11 
markdown-to-html 0.5.0 
open 2.0.4 
open-file 2.1.0 
```

**Comment by UziTech** [comment]
It looks like you have multiple packages that use the `open` host.

Your error:
`At There is already a URI host handler for the host open`

Remove the other one and open will work
